version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: migration-tracker-backend
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/app/data/migrationdb"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      # Allow external CORS access
      ALLOWED_ORIGINS: "http://localhost"
    volumes:
      - migration-data:/app/data
    ports:
      - "8080:8080"
    networks:
      - migration-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: migration-tracker-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - migration-network
    restart: unless-stopped

volumes:
  migration-data:

networks:
  migration-network:
    driver: bridge
